using System.Text.Json.Serialization;

namespace Salad.Cloud.IMDS.SDK.Models;

/// <summary>An API error. The `code` and `type` uniquely identify the type of the error. The `code` is a short value that may be used for programmatic error handling. The `type` is an absolute URL that may be resolved for more detailed information. Refer to the [SaladCloud IMDS reference](https://leaf.salad.com/l/saladcloud-imds-errors) for a list of the expected `code` and `type` values. Also, note that all properties are optional. Clients should implement robust error handling to account for unexpected errors.</summary>
public class SaladCloudImdsError
{
    /// <value>The error code that identifies the error type. This is a short value that may be used for programmatic error handling.</value>
    [JsonPropertyName("code"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Code { get; init; }

    /// <value>The human-readable explanation specific to this occurrence of the error.</value>
    [JsonPropertyName("detail"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Detail { get; init; }

    /// <value>The contextualized map of human-readable explanations specific to this occurrence of the error. This is often used to provide property-specific errors, such as validation errors. In these scenarios, the key is the property name and the value is an array of human-readable explanations specific to this property and this occurrence of the error.</value>
    [JsonPropertyName("errors"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Errors { get; init; }

    /// <value>The URI reference that identifies the specific occurrence of the error.</value>
    [JsonPropertyName("instance"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Instance { get; init; }

    /// <value>The HTTP status code generated by the origin server for this occurrence of the error.</value>
    [JsonPropertyName("status"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Status { get; init; }

    /// <value>The short, human-readable summary of the error type.</value>
    [JsonPropertyName("title"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Title { get; init; }

    /// <value>The URI reference that identifies the error type.</value>
    [JsonPropertyName("type"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Type_ { get; init; }

    // Constructor with defaults applied
    public SaladCloudImdsError(
        string? code = null,
        string? detail = null,
        object? errors = null,
        string? instance = null,
        long? status = null,
        string? title = null,
        string? type = null
    ) { }

    public override string ToString()
    {
        return $"{nameof(SaladCloudImdsError)} {{Code = {Code}, Detail = {Detail}, Errors = {Errors}, Instance = {Instance}, Status = {Status}, Title = {Title}, Type_ = {Type_}}}";
    }
}
